// <auto-generated />
namespace IndividualCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lxwxh_not_dimensions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lxwxh_not_dimensions));
        
        string IMigrationMetadata.Id
        {
            get { return "201910221938523_lxwxh_not_dimensions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
