// <auto-generated />
namespace IndividualCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class reformatted_Quote_to_Shipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(reformatted_Quote_to_Shipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201910241410564_reformatted_Quote_to_Shipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
