// <auto-generated />
namespace IndividualCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedQuoteId_QuoteFKtoShipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedQuoteId_QuoteFKtoShipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201910241501195_addedQuoteId_QuoteFKtoShipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
