// <auto-generated />
namespace IndividualCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class email_added_to_Customer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(email_added_to_Customer));
        
        string IMigrationMetadata.Id
        {
            get { return "201910241503403_email_added_to_Customer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
