// <auto-generated />
namespace IndividualCapstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class delAddy_PickupAddy_FK_addedToShipment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(delAddy_PickupAddy_FK_addedToShipment));
        
        string IMigrationMetadata.Id
        {
            get { return "201910241633204_delAddy_PickupAddy_FK_addedToShipment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
